#!/usr/bin/env python3
"""Generate additional high-value deck pages."""
import json, html, os

SITE = "/Users/stephaniedugas/Documents/stacked-site"

# Load existing template from generator
with open(os.path.join(SITE, "generate-decks.py"), "r") as f:
    content = f.read()
start = content.find('TEMPLATE = """') + len('TEMPLATE = """')
end = content.find('"""', start)
TEMPLATE = content[start:end]

DECKS = [
  {
    "slug": "act-vocabulary",
    "title": "ACT Vocabulary",
    "category": "Test Prep",
    "description": "High-frequency ACT vocabulary words to boost your English and Reading scores.",
    "meta_desc": "Free ACT vocabulary flashcards. 50 high-frequency words for the ACT English and Reading sections. Study online or import into Stacked.",
    "keywords": "ACT vocabulary, ACT vocab flashcards, ACT words, ACT prep, ACT study cards",
    "color": {"hex": "#007AFF", "r": 0.0, "g": 0.478, "b": 1.0},
    "cards": [
      ("Abstract", "Existing as an idea rather than having a physical existence"),
      ("Acknowledge", "To accept or admit the existence or truth of something"),
      ("Adversary", "An opponent or enemy"),
      ("Advocate", "A person who publicly supports a particular cause or policy"),
      ("Ambivalent", "Having mixed feelings or contradictory ideas about something"),
      ("Anecdote", "A short, interesting story about a real incident or person"),
      ("Assertion", "A confident and forceful statement of fact or belief"),
      ("Bias", "Prejudice in favor of or against something; unfair preference"),
      ("Brevity", "Concise and exact use of words; shortness of time"),
      ("Candor", "The quality of being open and honest in expression"),
      ("Compile", "To produce by assembling information from various sources"),
      ("Comprehensive", "Complete; including all or nearly all elements or aspects"),
      ("Concur", "To agree; to have the same opinion"),
      ("Contemplate", "To think deeply or carefully about something"),
      ("Conventional", "Based on what is generally done or believed; traditional"),
      ("Convey", "To communicate or make known; to transport"),
      ("Credible", "Able to be believed; convincing"),
      ("Criterion", "A standard by which something is judged (plural: criteria)"),
      ("Crucial", "Of great importance; critical"),
      ("Deception", "The act of causing someone to accept as true something that is false"),
      ("Deficiency", "A lack or shortage of something"),
      ("Depict", "To show or represent by drawing, painting, or describing"),
      ("Derive", "To obtain something from a specified source"),
      ("Diminish", "To make or become less; to reduce"),
      ("Discrepancy", "A lack of compatibility or similarity between facts or claims"),
      ("Disparity", "A great difference; inequality"),
      ("Diverse", "Showing a great deal of variety; different"),
      ("Elaborate", "Detailed and complicated in design; to develop in detail"),
      ("Elicit", "To draw out a response or reaction from someone"),
      ("Empathy", "The ability to understand and share the feelings of another"),
      ("Endorse", "To declare one's public approval or support of something"),
      ("Enhance", "To intensify, increase, or improve the quality of something"),
      ("Excerpt", "A short extract from a larger work"),
      ("Fluctuate", "To rise and fall irregularly in number or amount"),
      ("Fundamental", "Forming a necessary base or core; of central importance"),
      ("Generate", "To cause something to arise or come about; to produce"),
      ("Hypothesis", "A proposed explanation based on limited evidence; an educated guess"),
      ("Illustrate", "To explain or make clear by using examples or comparisons"),
      ("Impartial", "Treating all rivals or disputants equally; fair and just"),
      ("Implication", "A conclusion that can be drawn from something not explicitly stated"),
      ("Inevitable", "Certain to happen; unavoidable"),
      ("Integrity", "The quality of being honest and having strong moral principles"),
      ("Juxtapose", "To place close together for contrasting effect"),
      ("Mandatory", "Required by law or rules; compulsory"),
      ("Nostalgia", "A sentimental longing for the past"),
      ("Perspective", "A particular attitude toward or way of regarding something; a point of view"),
      ("Plausible", "Seeming reasonable or probable"),
      ("Prevalent", "Widespread in a particular area at a particular time"),
      ("Relevant", "Closely connected or appropriate to what is being discussed"),
      ("Substantiate", "To provide evidence to support or prove the truth of something"),
    ]
  },
  {
    "slug": "nclex-nursing",
    "title": "NCLEX-RN Nursing Essentials",
    "category": "Professional",
    "description": "Essential nursing concepts for the NCLEX-RN exam covering patient care, pharmacology, and clinical procedures.",
    "meta_desc": "Free NCLEX-RN flashcards. 50 essential nursing concepts for the NCLEX exam. Patient care, pharmacology, and clinical procedures.",
    "keywords": "NCLEX flashcards, NCLEX-RN study cards, nursing exam prep, nursing flashcards, NCLEX review",
    "color": {"hex": "#30D158", "r": 0.188, "g": 0.820, "b": 0.345},
    "cards": [
      ("ABCs of Assessment", "Airway, Breathing, Circulation — always assess in this priority order"),
      ("Maslow's in Nursing", "Physiological needs first, then Safety, Love/Belonging, Esteem, Self-Actualization — prioritize care accordingly"),
      ("Vital Signs Normal Ranges", "HR: 60-100, BP: <120/80, RR: 12-20, Temp: 97.8-99.1°F, SpO2: 95-100%"),
      ("Glasgow Coma Scale", "Eye (1-4) + Verbal (1-5) + Motor (1-6) = 3-15; <8 = severe brain injury, intubation needed"),
      ("Informed Consent", "Patient must understand procedure, risks, benefits, alternatives; must be competent; nurse witnesses signature, doctor explains"),
      ("HIPAA", "Protects patient health information; only share with those involved in care; violations have legal consequences"),
      ("Hand Hygiene", "Single most important measure to prevent infection; wash 20+ seconds; before/after patient contact; use alcohol-based if no visible soil"),
      ("Standard Precautions", "Treat all blood/body fluids as potentially infectious; gloves, hand hygiene; applies to ALL patients regardless of diagnosis"),
      ("Contact Precautions", "Gown + gloves for MRSA, C. diff, scabies; dedicated equipment; private room preferred"),
      ("Droplet Precautions", "Surgical mask within 3 feet; for flu, pertussis, meningitis; private room; no special air handling"),
      ("Airborne Precautions", "N95 respirator; negative pressure room; for TB, measles, varicella, COVID"),
      ("Medication Rights", "Right patient, Right drug, Right dose, Right route, Right time, Right documentation, Right reason, Right response"),
      ("Insulin Types", "Rapid (lispro, 15min onset), Short (regular, 30min), Intermediate (NPH, 2-4hr), Long (glargine, no peak, 24hr)"),
      ("Digoxin", "Cardiac glycoside; check apical HR for 1 full minute before giving; hold if HR < 60; monitor potassium (low K = toxicity)"),
      ("Warfarin (Coumadin)", "Anticoagulant; monitor PT/INR (therapeutic INR: 2-3); antidote: Vitamin K; avoid leafy greens (vitamin K foods)"),
      ("Heparin", "Anticoagulant; monitor aPTT (therapeutic: 1.5-2x control); antidote: protamine sulfate; SubQ or IV"),
      ("ACE Inhibitors (-pril)", "Lisinopril, enalapril; for HTN/heart failure; monitor for cough, hyperkalemia, angioedema; avoid in pregnancy"),
      ("Beta Blockers (-olol)", "Metoprolol, atenolol; slow HR, lower BP; hold if HR < 60 or BP < 90/60; don't stop abruptly"),
      ("Seizure Precautions", "Padded side rails, suction at bedside; during seizure: protect head, don't restrain, time it, turn on side after"),
      ("Fall Risk Assessment", "Morse Fall Scale; interventions: bed alarm, non-skid socks, call light within reach, toileting schedule"),
      ("Chest Tube Care", "Keep drainage system below chest level; monitor for air leak (bubbling); never clamp; assess drainage color/amount"),
      ("NG Tube Care", "Confirm placement by X-ray before first use; check residual before feeding; elevate HOB 30-45°; flush with water"),
      ("Foley Catheter Care", "Secure tubing; keep bag below bladder; peri-care every shift; monitor output; remove ASAP to prevent CAUTI"),
      ("Blood Transfusion", "Verify with 2 nurses; use Y-tubing with NS only; first 15 min = highest risk; monitor for fever, hives, dyspnea"),
      ("Transfusion Reaction", "Stop transfusion immediately; keep IV open with NS; notify MD; monitor vitals; send blood bag to lab"),
      ("Hyperglycemia Signs", "Polyuria, polydipsia, polyphagia, fruity breath (DKA), Kussmaul respirations, dehydration"),
      ("Hypoglycemia Signs", "Shakiness, sweating, tachycardia, confusion, irritability; treat with 15g fast-acting carbs, recheck in 15 min"),
      ("Heart Failure Left-Sided", "Pulmonary symptoms: dyspnea, orthopnea, crackles, cough, fatigue; backward failure into lungs"),
      ("Heart Failure Right-Sided", "Systemic symptoms: peripheral edema, JVD, hepatomegaly, weight gain; backward failure into body"),
      ("MI Symptoms", "Chest pain (crushing, radiating to arm/jaw), diaphoresis, nausea, dyspnea; women may have atypical symptoms"),
      ("Stroke Assessment", "FAST: Face drooping, Arm weakness, Speech difficulty, Time to call 911; ischemic vs hemorrhagic"),
      ("DVT Prevention", "SCDs, early ambulation, anticoagulants; assess for calf pain, warmth, swelling; elevate extremity"),
      ("Wound Care Basics", "Clean to dirty; moist wound healing; assess COCA: Color, Odor, Consistency, Amount of drainage"),
      ("Pain Assessment", "5th vital sign; use numeric (0-10), FACES, or FLACC scale; reassess after intervention"),
      ("Patient Education", "Teach-back method; assess readiness to learn; use simple language; document what was taught"),
      ("Delegation (RN)", "RN cannot delegate: assessment, teaching, evaluation, care planning; CAN delegate: vital signs, ADLs, I&O to UAP"),
      ("Electrolyte: Potassium (K+)", "Normal: 3.5-5.0 mEq/L; low = muscle weakness, dysrhythmias; high = peaked T waves, cardiac arrest; never push IV"),
      ("Electrolyte: Sodium (Na+)", "Normal: 135-145 mEq/L; low = confusion, seizures; high = thirst, dry mucous membranes; monitor fluid balance"),
      ("Electrolyte: Calcium (Ca2+)", "Normal: 8.5-10.5 mg/dL; low = Trousseau/Chvostek sign, tetany; high = kidney stones, bone pain"),
      ("Acid-Base: Metabolic Acidosis", "pH < 7.35, HCO3 < 22; causes: DKA, renal failure, diarrhea; Kussmaul respirations; treat underlying cause"),
      ("Acid-Base: Respiratory Alkalosis", "pH > 7.45, pCO2 < 35; cause: hyperventilation; have patient breathe into paper bag; address anxiety"),
      ("Pre-Op Nursing Care", "NPO status, consent signed, remove jewelry/dentures, mark surgical site, baseline vitals, anxiety management"),
      ("Post-Op Nursing Care", "Monitor vitals q15min, assess surgical site, pain management, I&O, encourage deep breathing/incentive spirometry"),
      ("Pressure Injury Prevention", "Reposition q2h; keep skin dry; adequate nutrition; Braden Scale assessment; pressure-relieving devices"),
      ("Isolation Gowning Order", "Put on: hand hygiene → gown → mask → goggles → gloves. Remove: gloves → goggles → gown → mask → hand hygiene"),
      ("SBAR Communication", "Situation (what's happening), Background (context), Assessment (your clinical judgment), Recommendation (what you need)"),
      ("Code Blue Response", "Call for help, begin CPR (30:2), attach AED/defibrillator, establish IV access, administer epinephrine q3-5min"),
      ("Pediatric Considerations", "Calculate meds by weight (mg/kg); smaller drug doses; assess fontanels in infants; use FLACC for pain"),
      ("Maternal: Fetal Heart Rate", "Normal FHR: 110-160 bpm; accelerations = reassuring; late decelerations = uteroplacental insufficiency (turn mom on left side, O2, stop Pitocin)"),
      ("End-of-Life Care", "Comfort measures; manage pain; family support; advance directives; hospice referral; pronouncement of death"),
    ]
  },
  {
    "slug": "comptia-a-plus",
    "title": "CompTIA A+ Core Concepts",
    "category": "Professional",
    "description": "Key concepts for the CompTIA A+ certification covering hardware, networking, operating systems, and troubleshooting.",
    "meta_desc": "Free CompTIA A+ flashcards. Hardware, networking, OS, and troubleshooting concepts for the A+ certification exam.",
    "keywords": "CompTIA A+ flashcards, A+ certification, A+ exam prep, CompTIA study cards, IT certification flashcards",
    "color": {"hex": "#5AC8FA", "r": 0.353, "g": 0.784, "b": 0.980},
    "cards": [
      ("RAM (Random Access Memory)", "Volatile memory; stores data temporarily while computer is on; DDR4/DDR5; measured in GB; more RAM = better multitasking"),
      ("ROM (Read-Only Memory)", "Non-volatile memory; stores firmware/BIOS; cannot be easily modified; retains data without power"),
      ("SSD vs HDD", "SSD: no moving parts, faster, more expensive, uses NAND flash. HDD: spinning platters, cheaper per GB, slower, mechanical failure risk"),
      ("BIOS vs UEFI", "BIOS: legacy firmware, MBR boot, 2TB limit. UEFI: modern replacement, GPT boot, secure boot, faster, supports larger drives"),
      ("CPU Components", "ALU (math/logic), Control Unit (directs operations), Cache (L1/L2/L3 fast memory), Registers (tiny fast storage)"),
      ("Motherboard Form Factors", "ATX (standard, most common), Micro-ATX (smaller), Mini-ITX (smallest); determines case compatibility and expansion slots"),
      ("PCIe (PCI Express)", "High-speed expansion bus; x1, x4, x8, x16 lanes; used for GPUs, SSDs, NICs; each gen doubles bandwidth"),
      ("RAID Levels", "RAID 0: striping (fast, no redundancy). RAID 1: mirroring (redundancy). RAID 5: striping + parity (min 3 drives). RAID 10: mirror + stripe"),
      ("TCP vs UDP", "TCP: connection-oriented, reliable, ordered, slower (HTTP, FTP, email). UDP: connectionless, faster, no guarantee (DNS, streaming, gaming)"),
      ("OSI Model", "7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application. 'Please Do Not Throw Sausage Pizza Away'"),
      ("IP Address Classes", "Class A: 1-126 (large networks). Class B: 128-191 (medium). Class C: 192-223 (small). Private: 10.x, 172.16-31.x, 192.168.x"),
      ("Subnet Mask", "Determines network vs host portion of IP; /24 = 255.255.255.0 (254 hosts); /16 = 255.255.0.0 (65,534 hosts)"),
      ("DNS", "Domain Name System; translates domain names to IP addresses; port 53; uses UDP primarily; hierarchical (root → TLD → domain)"),
      ("DHCP", "Dynamic Host Configuration Protocol; automatically assigns IP addresses; port 67/68; DORA process: Discover, Offer, Request, Acknowledge"),
      ("Common Ports", "HTTP: 80, HTTPS: 443, FTP: 20/21, SSH: 22, Telnet: 23, SMTP: 25, DNS: 53, RDP: 3389, SMB: 445"),
      ("Windows Command Line", "ipconfig (network info), ping (test connectivity), tracert (trace route), nslookup (DNS query), chkdsk (disk check), sfc /scannow (system files)"),
      ("Linux Commands", "ls (list), cd (change dir), sudo (run as root), chmod (permissions), grep (search text), apt/yum (install packages)"),
      ("File Systems", "NTFS: Windows, permissions, encryption, large files. FAT32: cross-platform, 4GB file limit. ext4: Linux. APFS: macOS"),
      ("Malware Types", "Virus (needs host file), Worm (self-replicating), Trojan (disguised), Ransomware (encrypts files), Spyware (monitors activity), Rootkit (hides deep)"),
      ("Encryption", "Symmetric: same key encrypts/decrypts (AES, DES). Asymmetric: public/private key pair (RSA). Hashing: one-way (SHA, MD5)"),
      ("802.11 Wi-Fi Standards", "802.11n (Wi-Fi 4): 600 Mbps. 802.11ac (Wi-Fi 5): 3.5 Gbps, 5GHz. 802.11ax (Wi-Fi 6): 9.6 Gbps, 2.4/5/6GHz"),
      ("Troubleshooting Methodology", "1) Identify problem 2) Theory of cause 3) Test theory 4) Plan of action 5) Implement 6) Verify 7) Document"),
      ("Printer Types", "Laser: toner, fast, high quality. Inkjet: liquid ink, photo quality, slower. Thermal: heat-sensitive paper, receipts. Impact: dot matrix, carbon copies"),
      ("Power Supply (PSU)", "Converts AC to DC; measured in watts; 80 Plus efficiency ratings; modular vs non-modular cables; ATX 24-pin connector"),
      ("Display Connectors", "HDMI: audio+video, most common. DisplayPort: high refresh, daisy-chain. VGA: analog, legacy. DVI: digital/analog, older. USB-C: modern, versatile"),
      ("Cloud Computing Models", "IaaS (VMs, storage), PaaS (dev platforms), SaaS (apps). Public (shared), Private (dedicated), Hybrid (mix)"),
      ("Virtualization", "Running multiple OS on one physical machine; hypervisor manages VMs; Type 1 (bare metal), Type 2 (hosted); saves hardware costs"),
      ("Mobile Device Security", "Screen lock, remote wipe, full device encryption, MDM (Mobile Device Management), biometrics, app permissions"),
      ("ESD Prevention", "Electrostatic Discharge can damage components; use anti-static wrist strap; touch case metal; work on anti-static mat"),
      ("Backup Types", "Full: everything (slow, complete). Incremental: changes since last backup (fast, complex restore). Differential: changes since last full (moderate)"),
    ]
  },
  {
    "slug": "organic-chemistry",
    "title": "Organic Chemistry Essentials",
    "category": "College",
    "description": "Core organic chemistry concepts including functional groups, reactions, and nomenclature.",
    "meta_desc": "Free organic chemistry flashcards. Functional groups, reactions, nomenclature, and mechanisms. Study for orgo online or import into Stacked.",
    "keywords": "organic chemistry flashcards, orgo flashcards, organic chem study cards, functional groups, ochem",
    "color": {"hex": "#AF52DE", "r": 0.686, "g": 0.322, "b": 0.969},
    "cards": [
      ("Alkane", "Single bonds only (C-C); saturated hydrocarbon; suffix: -ane; general formula: CnH2n+2; sp3 hybridized"),
      ("Alkene", "Contains C=C double bond; unsaturated; suffix: -ene; general formula: CnH2n; sp2 hybridized; undergoes addition reactions"),
      ("Alkyne", "Contains C≡C triple bond; suffix: -yne; general formula: CnH2n-2; sp hybridized; linear geometry"),
      ("Alcohol (-OH)", "Hydroxyl group; suffix: -ol; hydrogen bonding = higher boiling point; primary, secondary, tertiary based on carbon substitution"),
      ("Aldehyde (-CHO)", "Carbonyl at end of chain; suffix: -al; can be oxidized to carboxylic acid; Tollens test (silver mirror)"),
      ("Ketone (C=O)", "Carbonyl within chain; suffix: -one; cannot be easily oxidized; common solvent (acetone)"),
      ("Carboxylic Acid (-COOH)", "Suffix: -oic acid; acidic (donates H+); forms esters with alcohols; found in vinegar (acetic acid)"),
      ("Ester (-COOR)", "Formed from acid + alcohol (condensation); suffix: -oate; fruity smells; found in fats and oils"),
      ("Amine (-NH2)", "Contains nitrogen; suffix: -amine; basic (accepts H+); found in amino acids and drugs"),
      ("Ether (-O-)", "Oxygen between two carbons; relatively inert; lower boiling point than alcohols; common solvent (diethyl ether)"),
      ("SN1 Reaction", "Substitution, nucleophilic, unimolecular; two steps; carbocation intermediate; favored by tertiary substrates, polar protic solvents; racemization"),
      ("SN2 Reaction", "Substitution, nucleophilic, bimolecular; one step, backside attack; favored by primary substrates, strong nucleophile, polar aprotic solvents; inversion"),
      ("E1 Elimination", "Unimolecular; two steps; carbocation intermediate; favored by tertiary, weak base, heat; Zaitsev product (more substituted alkene)"),
      ("E2 Elimination", "Bimolecular; one step, concerted; favored by strong base, heat, anti-periplanar geometry; Zaitsev product"),
      ("Markovnikov's Rule", "In HX addition to alkenes, H adds to carbon with MORE hydrogens; positive charge on more substituted carbon (more stable)"),
      ("Anti-Markovnikov", "Opposite of Markovnikov; occurs with peroxides (HBr + ROOR); hydroboration-oxidation gives anti-Markovnikov alcohol"),
      ("Zaitsev's Rule", "In elimination reactions, the major product is the more substituted (more stable) alkene"),
      ("Chirality", "A molecule that is non-superimposable on its mirror image; has a chiral center (4 different groups on carbon); R/S configuration"),
      ("Enantiomers", "Mirror-image stereoisomers; same physical properties except optical rotation; opposite R/S configuration"),
      ("Diastereomers", "Stereoisomers that are NOT mirror images; different physical properties; different R/S at some but not all chiral centers"),
      ("Hybridization", "sp3: tetrahedral, 109.5°. sp2: trigonal planar, 120°. sp: linear, 180°. Determines molecular geometry"),
      ("Electronegativity in Organic", "F > O > N > Cl > Br > C > H; determines bond polarity and acidity; inductive effect"),
      ("Resonance", "Delocalization of electrons across adjacent p orbitals; stabilizes molecules; shown with multiple Lewis structures"),
      ("Carbocation Stability", "Tertiary > Secondary > Primary > Methyl; more substituted = more stable; hyperconjugation and inductive effects"),
      ("Acidity Trends", "More stable conjugate base = stronger acid; factors: electronegativity, size, resonance, induction, hybridization"),
      ("Hydrogen Bonding", "Strong intermolecular force; requires H bonded to F, O, or N; increases boiling point; key in DNA, proteins, water"),
      ("IUPAC Nomenclature Steps", "1) Find longest chain 2) Number from end nearest substituent 3) Name substituents 4) Assign numbers 5) Alphabetize"),
      ("Aromatic Compounds", "Benzene ring (C6H6); planar, cyclic, conjugated; 4n+2 pi electrons (Hückel's rule); very stable; undergoes EAS, not addition"),
      ("Electrophilic Aromatic Substitution", "Aromatic ring attacks electrophile; H replaced by E+; types: halogenation, nitration, sulfonation, Friedel-Crafts"),
      ("Oxidation in Organic", "Loss of H or gain of O; primary alcohol → aldehyde → carboxylic acid; secondary alcohol → ketone; use KMnO4, CrO3, PCC"),
    ]
  },
  {
    "slug": "statistics-101",
    "title": "Statistics 101",
    "category": "College",
    "description": "Introductory statistics concepts including descriptive stats, probability, distributions, and hypothesis testing.",
    "meta_desc": "Free Statistics 101 flashcards. Descriptive stats, probability, distributions, and hypothesis testing. Study online or import into Stacked.",
    "keywords": "statistics flashcards, stats 101, statistics study cards, probability flashcards, hypothesis testing",
    "color": {"hex": "#FF9F0A", "r": 1.0, "g": 0.624, "b": 0.039},
    "cards": [
      ("Mean", "Average; sum of all values divided by the number of values; sensitive to outliers"),
      ("Median", "Middle value when data is ordered; not affected by outliers; better measure for skewed data"),
      ("Mode", "Most frequently occurring value; can have multiple modes or no mode; only measure for categorical data"),
      ("Standard Deviation", "Measure of spread around the mean; square root of variance; low SD = data clustered near mean"),
      ("Variance", "Average of squared deviations from the mean; SD²; measures data spread"),
      ("Range", "Maximum value minus minimum value; simplest measure of spread; sensitive to outliers"),
      ("Normal Distribution", "Bell-shaped, symmetric curve; mean = median = mode; 68-95-99.7 rule; many natural phenomena follow this"),
      ("68-95-99.7 Rule", "In a normal distribution: 68% within 1 SD, 95% within 2 SD, 99.7% within 3 SD of the mean"),
      ("Z-Score", "Number of standard deviations a value is from the mean; Z = (X - μ) / σ; positive = above mean, negative = below"),
      ("Probability", "Likelihood of an event; ranges from 0 (impossible) to 1 (certain); P(A) = favorable outcomes / total outcomes"),
      ("Independent Events", "Occurrence of one does not affect the other; P(A and B) = P(A) × P(B); example: coin flips"),
      ("Mutually Exclusive Events", "Cannot occur simultaneously; P(A or B) = P(A) + P(B); example: rolling a 1 or a 6 on one die"),
      ("Conditional Probability", "P(A|B) = probability of A given B occurred; P(A|B) = P(A and B) / P(B); Bayes' theorem"),
      ("Population vs Sample", "Population: entire group of interest. Sample: subset of population. Statistics estimate parameters"),
      ("Parameter vs Statistic", "Parameter: describes population (μ, σ). Statistic: describes sample (x̄, s). We use statistics to estimate parameters"),
      ("Sampling Bias", "When sample does not represent the population; types: selection bias, response bias, voluntary response bias"),
      ("Central Limit Theorem", "As sample size increases, sampling distribution of the mean approaches normal regardless of population shape; n ≥ 30"),
      ("Confidence Interval", "Range of values likely to contain the population parameter; 95% CI means 95% of intervals would capture the true value"),
      ("Margin of Error", "Half-width of confidence interval; decreases with larger sample size; affected by confidence level and variability"),
      ("Hypothesis Testing", "Null hypothesis (H₀): no effect/difference. Alternative (Hₐ): there is an effect. Collect data, calculate p-value, decide"),
      ("P-Value", "Probability of observing data as extreme as the sample, assuming H₀ is true; small p-value (< α) = reject H₀"),
      ("Significance Level (α)", "Threshold for rejecting H₀; typically 0.05 (5%); if p-value < α, result is 'statistically significant'"),
      ("Type I Error", "Rejecting H₀ when it is actually true (false positive); probability = α; 'seeing an effect that isn't there'"),
      ("Type II Error", "Failing to reject H₀ when it is actually false (false negative); probability = β; 'missing a real effect'"),
      ("Correlation Coefficient (r)", "Measures linear relationship strength; -1 to +1; |r| > 0.7 strong, 0.3-0.7 moderate, < 0.3 weak"),
      ("Correlation vs Causation", "Correlation does NOT imply causation; confounding variables may explain the relationship; need controlled experiments"),
      ("Linear Regression", "ŷ = a + bx; predicts dependent variable from independent; b = slope (change in y per unit x); a = y-intercept"),
      ("R-Squared (R²)", "Proportion of variance in y explained by x; ranges 0-1; R² = 0.85 means 85% of variation explained by the model"),
      ("Chi-Square Test", "Tests association between categorical variables; compares observed vs expected frequencies; larger χ² = more evidence of association"),
      ("T-Test", "Compares means; one-sample (vs known value), two-sample (two groups), paired (before/after); uses t-distribution for small samples"),
    ]
  },
  {
    "slug": "german-101",
    "title": "German 101 — Common Phrases",
    "category": "Languages",
    "description": "Essential German phrases and vocabulary for beginners and travelers.",
    "meta_desc": "Free German flashcards for beginners. Essential phrases and vocabulary words. Study online or import into Stacked.",
    "keywords": "German flashcards, learn German, German vocabulary, German 101, basic German phrases",
    "color": {"hex": "#FF375F", "r": 1.0, "g": 0.216, "b": 0.373},
    "cards": [
      ("Hello", "Hallo"),
      ("Good morning", "Guten Morgen"),
      ("Good evening", "Guten Abend"),
      ("Goodbye", "Auf Wiedersehen / Tschüss"),
      ("Please", "Bitte"),
      ("Thank you", "Danke"),
      ("You're welcome", "Bitte schön"),
      ("Yes", "Ja"),
      ("No", "Nein"),
      ("Excuse me", "Entschuldigung"),
      ("I'm sorry", "Es tut mir leid"),
      ("How are you?", "Wie geht es Ihnen? / Wie geht's?"),
      ("I'm fine, thanks", "Mir geht es gut, danke"),
      ("What is your name?", "Wie heißen Sie? / Wie heißt du?"),
      ("My name is...", "Ich heiße..."),
      ("I don't understand", "Ich verstehe nicht"),
      ("Do you speak English?", "Sprechen Sie Englisch?"),
      ("Where is...?", "Wo ist...?"),
      ("How much does it cost?", "Wie viel kostet das?"),
      ("Water", "Wasser"),
      ("Beer", "Bier"),
      ("The check, please", "Die Rechnung, bitte"),
      ("One", "Eins"),
      ("Two", "Zwei"),
      ("Three", "Drei"),
      ("Four", "Vier"),
      ("Five", "Fünf"),
      ("Monday", "Montag"),
      ("Tuesday", "Dienstag"),
      ("Wednesday", "Mittwoch"),
    ]
  },
  {
    "slug": "korean-basics",
    "title": "Korean Basics — Common Phrases",
    "category": "Languages",
    "description": "Essential Korean phrases with romanization for beginners learning Korean.",
    "meta_desc": "Free Korean flashcards. Essential phrases with romanization for beginners. Study online or import into Stacked.",
    "keywords": "Korean flashcards, learn Korean, Korean vocabulary, Korean basics, Korean phrases",
    "color": {"hex": "#007AFF", "r": 0.0, "g": 0.478, "b": 1.0},
    "cards": [
      ("Hello (formal)", "안녕하세요 (annyeonghaseyo)"),
      ("Hello (casual)", "안녕 (annyeong)"),
      ("Thank you", "감사합니다 (gamsahamnida)"),
      ("You're welcome", "천만에요 (cheonmaneyo)"),
      ("I'm sorry", "죄송합니다 (joesonghamnida)"),
      ("Yes", "네 (ne) / 예 (ye)"),
      ("No", "아니요 (aniyo)"),
      ("Excuse me", "실례합니다 (sillyehamnida)"),
      ("Goodbye (to person leaving)", "안녕히 가세요 (annyeonghi gaseyo)"),
      ("Goodbye (to person staying)", "안녕히 계세요 (annyeonghi gyeseyo)"),
      ("How are you?", "잘 지내세요? (jal jinaeseyo?)"),
      ("I'm fine", "잘 지내요 (jal jinaeyo)"),
      ("What is your name?", "이름이 뭐예요? (ireumi mwoyeyo?)"),
      ("My name is...", "제 이름은...이에요 (je ireumeun...ieyo)"),
      ("I don't understand", "이해 못 해요 (ihae mot haeyo)"),
      ("Please give me...", "...주세요 (...juseyo)"),
      ("How much is it?", "얼마예요? (eolmayeyo?)"),
      ("Water", "물 (mul)"),
      ("Food", "음식 (eumsik)"),
      ("Delicious", "맛있어요 (masisseoyo)"),
      ("One", "하나 (hana) / 일 (il)"),
      ("Two", "둘 (dul) / 이 (i)"),
      ("Three", "셋 (set) / 삼 (sam)"),
      ("I love you", "사랑해요 (saranghaeyo)"),
      ("Friend", "친구 (chingu)"),
      ("Student", "학생 (haksaeng)"),
      ("School", "학교 (hakgyo)"),
      ("To eat", "먹다 (meokda)"),
      ("To go", "가다 (gada)"),
      ("Korea", "한국 (hanguk)"),
    ]
  },
  {
    "slug": "accounting-101",
    "title": "Accounting 101",
    "category": "College",
    "description": "Fundamental accounting concepts including the accounting equation, financial statements, and key terms.",
    "meta_desc": "Free Accounting 101 flashcards. The accounting equation, financial statements, debits and credits. Study online or import into Stacked.",
    "keywords": "accounting flashcards, accounting 101, bookkeeping flashcards, financial accounting, debits and credits",
    "color": {"hex": "#30D158", "r": 0.188, "g": 0.820, "b": 0.345},
    "cards": [
      ("Accounting Equation", "Assets = Liabilities + Owner's Equity; must ALWAYS balance; foundation of double-entry bookkeeping"),
      ("Assets", "Resources owned by the business; examples: cash, accounts receivable, inventory, equipment, buildings"),
      ("Liabilities", "Debts owed by the business; examples: accounts payable, loans payable, wages payable, taxes payable"),
      ("Owner's Equity", "Owner's claim on assets after liabilities; also called stockholders' equity; includes retained earnings"),
      ("Revenue", "Income earned from business operations; increases equity; recognized when earned (accrual basis), not when cash received"),
      ("Expenses", "Costs incurred to generate revenue; decrease equity; matched to the revenue they help generate"),
      ("Debit", "Left side of a T-account; increases assets and expenses; decreases liabilities, equity, and revenue"),
      ("Credit", "Right side of a T-account; increases liabilities, equity, and revenue; decreases assets and expenses"),
      ("Double-Entry Bookkeeping", "Every transaction affects at least two accounts; total debits must equal total credits; keeps equation balanced"),
      ("Income Statement", "Reports revenue and expenses over a period; shows net income (profit) or net loss; Revenue - Expenses = Net Income"),
      ("Balance Sheet", "Reports assets, liabilities, and equity at a point in time; a snapshot of financial position; must balance"),
      ("Cash Flow Statement", "Reports cash inflows and outflows; three sections: Operating, Investing, Financing activities"),
      ("Accounts Receivable", "Money owed TO the business by customers; asset account; arises from credit sales"),
      ("Accounts Payable", "Money the business OWES to suppliers; liability account; arises from credit purchases"),
      ("Depreciation", "Allocating cost of a long-term asset over its useful life; not a cash expense; methods: straight-line, declining balance"),
      ("Accrual Accounting", "Revenue recognized when earned, expenses when incurred; regardless of when cash changes hands; GAAP required"),
      ("Cash Basis Accounting", "Revenue recognized when cash received, expenses when cash paid; simpler but less accurate; used by small businesses"),
      ("GAAP", "Generally Accepted Accounting Principles; standard framework for financial accounting in the US; set by FASB"),
      ("Trial Balance", "List of all accounts and their balances; debits must equal credits; used to check for errors before financial statements"),
      ("Journal Entry", "The initial recording of a transaction; includes date, accounts, amounts, and description; chronological order"),
      ("Ledger", "Collection of all accounts; each account shows all transactions affecting it; organized by account number"),
      ("Net Income", "Revenue minus expenses; the 'bottom line'; positive = profit, negative = loss; flows to retained earnings"),
      ("Retained Earnings", "Accumulated profits not distributed as dividends; part of equity; increases with net income, decreases with dividends"),
      ("Working Capital", "Current Assets minus Current Liabilities; measures short-term financial health; positive = can pay near-term debts"),
      ("Current Ratio", "Current Assets / Current Liabilities; measures liquidity; > 1 means company can cover short-term obligations"),
      ("Inventory", "Goods available for sale; asset account; methods: FIFO (first in first out), LIFO (last in first out), weighted average"),
      ("Cost of Goods Sold (COGS)", "Direct costs of producing goods sold; Beginning Inventory + Purchases - Ending Inventory; subtracted from revenue for gross profit"),
      ("Gross Profit", "Revenue minus Cost of Goods Sold; measures profitability before operating expenses"),
      ("Break-Even Point", "Sales volume where total revenue equals total costs; no profit or loss; Fixed Costs / (Price - Variable Cost per Unit)"),
      ("Audit", "Independent examination of financial statements; ensures accuracy and compliance with GAAP; external vs internal"),
    ]
  },
  {
    "slug": "ap-calculus",
    "title": "AP Calculus AB",
    "category": "AP Exams",
    "description": "Key concepts for AP Calculus AB including limits, derivatives, integrals, and the fundamental theorem.",
    "meta_desc": "Free AP Calculus AB flashcards. Limits, derivatives, integrals, and key theorems. Study for the AP Calc exam online or import into Stacked.",
    "keywords": "AP Calculus flashcards, AP Calc AB, calculus study cards, derivatives flashcards, integrals flashcards",
    "color": {"hex": "#AF52DE", "r": 0.686, "g": 0.322, "b": 0.969},
    "cards": [
      ("Limit Definition", "The value a function approaches as x approaches a specific value; lim x→a f(x) = L"),
      ("Continuity", "f(x) is continuous at x=a if: f(a) exists, lim x→a f(x) exists, and lim x→a f(x) = f(a)"),
      ("Derivative Definition", "f'(x) = lim h→0 [f(x+h) - f(x)] / h; represents instantaneous rate of change; slope of tangent line"),
      ("Power Rule", "d/dx [xⁿ] = nxⁿ⁻¹; example: d/dx [x³] = 3x²"),
      ("Product Rule", "d/dx [f·g] = f'g + fg'; 'first times derivative of second plus second times derivative of first'"),
      ("Quotient Rule", "d/dx [f/g] = (f'g - fg') / g²; 'low d-high minus high d-low over low squared'"),
      ("Chain Rule", "d/dx [f(g(x))] = f'(g(x)) · g'(x); derivative of outer times derivative of inner"),
      ("d/dx [sin x]", "cos x"),
      ("d/dx [cos x]", "-sin x"),
      ("d/dx [tan x]", "sec²x"),
      ("d/dx [eˣ]", "eˣ (the only function that is its own derivative)"),
      ("d/dx [ln x]", "1/x"),
      ("Implicit Differentiation", "Differentiate both sides with respect to x; treat y as a function of x; multiply dy/dx when differentiating y terms"),
      ("Related Rates", "Find how rates of change are connected; differentiate equation with respect to time; solve for unknown rate"),
      ("Mean Value Theorem", "If f is continuous on [a,b] and differentiable on (a,b), there exists c where f'(c) = [f(b)-f(a)]/(b-a)"),
      ("Critical Points", "Where f'(x) = 0 or f'(x) is undefined; candidates for local maxima and minima"),
      ("First Derivative Test", "f' changes + to - at c → local max. f' changes - to + at c → local min"),
      ("Second Derivative Test", "f''(c) > 0 → concave up → local min. f''(c) < 0 → concave down → local max"),
      ("Inflection Point", "Where concavity changes; f''(x) = 0 or undefined AND concavity actually changes"),
      ("Antiderivative", "Reverse of derivative; F'(x) = f(x); ∫f(x)dx = F(x) + C; always add constant C"),
      ("∫xⁿ dx", "xⁿ⁺¹/(n+1) + C (n ≠ -1); reverse of power rule"),
      ("∫1/x dx", "ln|x| + C"),
      ("∫eˣ dx", "eˣ + C"),
      ("∫sin x dx", "-cos x + C"),
      ("∫cos x dx", "sin x + C"),
      ("U-Substitution", "∫f(g(x))g'(x)dx; let u = g(x), du = g'(x)dx; reverse of chain rule"),
      ("Fundamental Theorem (Part 1)", "If F(x) = ∫ₐˣ f(t)dt, then F'(x) = f(x); derivative of an integral returns the original function"),
      ("Fundamental Theorem (Part 2)", "∫ₐᵇ f(x)dx = F(b) - F(a); definite integral = antiderivative evaluated at endpoints"),
      ("Area Under Curve", "∫ₐᵇ f(x)dx gives signed area between f(x) and x-axis from a to b; negative below x-axis"),
      ("Average Value", "Average value of f on [a,b] = (1/(b-a)) · ∫ₐᵇ f(x)dx"),
    ]
  },
  {
    "slug": "sociology-101",
    "title": "Sociology 101",
    "category": "College",
    "description": "Key sociology concepts including social structure, culture, inequality, and major theoretical perspectives.",
    "meta_desc": "Free Sociology 101 flashcards. Social structure, culture, inequality, and sociological theories. Study online or import into Stacked.",
    "keywords": "sociology flashcards, sociology 101, intro sociology, social studies flashcards, sociology terms",
    "color": {"hex": "#5AC8FA", "r": 0.353, "g": 0.784, "b": 0.980},
    "cards": [
      ("Sociology", "The scientific study of human society, social behavior, and social structures"),
      ("Sociological Imagination", "C. Wright Mills; ability to see the connection between personal troubles and larger social issues"),
      ("Functionalism", "Society is a system of interconnected parts that work together; each institution serves a function; Durkheim, Parsons"),
      ("Conflict Theory", "Society is characterized by inequality and competition for resources; power dynamics shape social life; Karl Marx"),
      ("Symbolic Interactionism", "Society is constructed through everyday interactions and shared meanings; micro-level analysis; Mead, Blumer"),
      ("Culture", "Shared beliefs, values, norms, and material objects of a group; learned, not biological; shapes behavior"),
      ("Ethnocentrism", "Judging another culture by the standards of your own; believing your culture is superior"),
      ("Cultural Relativism", "Understanding a culture on its own terms; not judging other cultures by your own standards"),
      ("Socialization", "The lifelong process of learning social norms, values, and behaviors; primary agents: family, school, peers, media"),
      ("Social Stratification", "System by which society ranks people in a hierarchy; based on wealth, power, prestige; can be open or closed"),
      ("Social Mobility", "Movement between social classes; upward, downward, or horizontal; intergenerational vs intragenerational"),
      ("Social Class", "Group of people with similar levels of wealth, power, and prestige; upper, middle, working, lower class"),
      ("Deviance", "Behavior that violates social norms; can be criminal or non-criminal; defined by society, not inherent"),
      ("Labeling Theory", "Being labeled as deviant leads to more deviance; self-fulfilling prophecy; Becker; 'the label becomes the identity'"),
      ("Gender Roles", "Socially constructed expectations for behavior based on gender; vary across cultures and time periods"),
      ("Patriarchy", "Social system in which men hold primary power and authority; affects politics, property, family, social roles"),
      ("Race vs Ethnicity", "Race: socially constructed category based on physical traits. Ethnicity: shared cultural heritage, language, traditions"),
      ("Prejudice", "Preconceived opinion not based on reason or experience; attitude; can be positive or negative"),
      ("Discrimination", "Unequal treatment based on group membership; action/behavior; individual vs institutional"),
      ("Institutional Racism", "Racial inequality embedded in social institutions (education, justice, housing); systemic, not just individual"),
      ("Anomie", "Durkheim; breakdown of social norms and values; feeling of disconnection; common during rapid social change"),
      ("Bureaucracy", "Weber; formal organization with hierarchy, rules, specialization, impersonality; efficient but can be rigid"),
      ("Social Institution", "Organized pattern of beliefs and behaviors focused on meeting social needs: family, education, religion, government, economy"),
      ("Primary Group", "Small, close-knit group with intimate relationships; family, close friends; provides emotional support"),
      ("Secondary Group", "Larger, more impersonal group; goal-oriented; coworkers, classmates; less emotional connection"),
      ("Groupthink", "Tendency for group members to conform to consensus; suppresses critical thinking; leads to poor decisions"),
      ("Urbanization", "Movement of populations from rural to urban areas; driven by industrialization; creates density, diversity"),
      ("Globalization", "Increasing interconnection of world's economies, cultures, and populations; spread of ideas, goods, and technology"),
      ("Social Control", "Mechanisms society uses to enforce norms; formal (laws, police) and informal (shaming, gossip, peer pressure)"),
      ("Verstehen", "Weber; empathetic understanding; researchers should try to understand the meaning people attach to their actions"),
    ]
  },
  {
    "slug": "comptia-security-plus",
    "title": "CompTIA Security+ Essentials",
    "category": "Professional",
    "description": "Core cybersecurity concepts for the CompTIA Security+ certification exam.",
    "meta_desc": "Free CompTIA Security+ flashcards. Core cybersecurity concepts for the Security+ certification. Threats, cryptography, and network security.",
    "keywords": "CompTIA Security+ flashcards, Security+ study cards, cybersecurity flashcards, Security+ exam prep, SY0-701",
    "color": {"hex": "#FF375F", "r": 1.0, "g": 0.216, "b": 0.373},
    "cards": [
      ("CIA Triad", "Confidentiality (only authorized access), Integrity (data is accurate/unmodified), Availability (systems are accessible when needed)"),
      ("Authentication Factors", "Something you know (password), Something you have (token/phone), Something you are (biometrics), Somewhere you are (location)"),
      ("MFA (Multi-Factor Authentication)", "Using two or more authentication factors; password + phone code; significantly reduces unauthorized access"),
      ("Phishing", "Social engineering via email; fake messages trick users into revealing credentials or clicking malicious links; most common attack vector"),
      ("Spear Phishing", "Targeted phishing aimed at a specific person or organization; uses personal details to appear legitimate"),
      ("Social Engineering", "Manipulating people into revealing information or performing actions; pretexting, baiting, tailgating, quid pro quo"),
      ("Malware", "Malicious software: viruses, worms, trojans, ransomware, spyware, rootkits, keyloggers, adware"),
      ("Ransomware", "Encrypts victim's files; demands payment for decryption key; prevent with backups, patching, and email filtering"),
      ("Zero-Day Vulnerability", "Unpatched security flaw unknown to the vendor; no fix available yet; highly valuable to attackers"),
      ("Firewall", "Controls incoming/outgoing network traffic based on rules; stateful (tracks connections) vs stateless; hardware or software"),
      ("IDS vs IPS", "IDS: Intrusion Detection System (monitors and alerts). IPS: Intrusion Prevention System (monitors AND blocks). Inline vs passive"),
      ("VPN", "Virtual Private Network; encrypts traffic between endpoints; creates secure tunnel over public internet; site-to-site or remote access"),
      ("Symmetric Encryption", "Same key encrypts and decrypts; fast; examples: AES (standard), DES (legacy), 3DES; key distribution is the challenge"),
      ("Asymmetric Encryption", "Public key encrypts, private key decrypts; slower; examples: RSA, ECC; used for key exchange, digital signatures"),
      ("Hashing", "One-way function producing fixed-length output; SHA-256, MD5 (insecure); used for password storage, file integrity"),
      ("Digital Certificate", "Binds a public key to an identity; issued by Certificate Authority (CA); enables HTTPS; contains subject, issuer, expiry, public key"),
      ("PKI (Public Key Infrastructure)", "Framework for managing digital certificates and encryption keys; includes CAs, registration authorities, certificate revocation"),
      ("Least Privilege", "Users should have only the minimum access needed for their job; reduces attack surface; review regularly"),
      ("Defense in Depth", "Multiple layers of security controls; if one layer fails, others protect; physical, technical, and administrative controls"),
      ("Risk Assessment", "Identifying threats, vulnerabilities, and their potential impact; Risk = Threat × Vulnerability × Impact; prioritize mitigation"),
      ("Vulnerability Scanning", "Automated tool that identifies known vulnerabilities in systems; Nessus, Qualys; run regularly; different from penetration testing"),
      ("Penetration Testing", "Authorized simulated attack to find exploitable vulnerabilities; black box (no info), white box (full info), gray box (partial)"),
      ("SIEM", "Security Information and Event Management; collects and analyzes logs from across the network; real-time alerting; Splunk, QRadar"),
      ("Incident Response Steps", "1) Preparation 2) Identification 3) Containment 4) Eradication 5) Recovery 6) Lessons Learned"),
      ("DDoS Attack", "Distributed Denial of Service; overwhelms target with traffic from many sources (botnet); disrupts availability"),
      ("SQL Injection", "Inserting malicious SQL into input fields to manipulate databases; prevented with parameterized queries and input validation"),
      ("XSS (Cross-Site Scripting)", "Injecting malicious scripts into web pages viewed by others; stored, reflected, or DOM-based; sanitize user input"),
      ("Access Control Models", "DAC (owner decides), MAC (labels/clearances), RBAC (role-based), ABAC (attribute-based)"),
      ("Business Continuity Plan", "Strategy to maintain operations during and after a disaster; includes BIA, recovery procedures, communication plan"),
      ("Backup Strategy: 3-2-1", "3 copies of data, on 2 different media types, with 1 offsite/cloud copy; protects against any single point of failure"),
    ]
  },
]

# Generate all deck pages
for deck in DECKS:
    card_html_lines = []
    for front, back in deck["cards"]:
        f = html.escape(front)
        b = html.escape(back)
        card_html_lines.append(f'        <div class="card-item"><div class="card-front">{f}</div><div class="card-back">{b}</div></div>')

    card_html = "\n".join(card_html_lines)

    deck_json = json.dumps({
        "title": deck["title"],
        "cards": deck["cards"],
        "color": {"red": deck["color"]["r"], "green": deck["color"]["g"], "blue": deck["color"]["b"]}
    })

    page_title = f"Free {deck['title']} Flashcards"

    page = TEMPLATE.format(
        page_title=page_title,
        meta_desc=deck["meta_desc"],
        keywords=deck["keywords"],
        slug=deck["slug"],
        title=deck["title"],
        description=deck["description"],
        category=deck["category"],
        card_count=len(deck["cards"]),
        card_html=card_html,
        deck_json=deck_json,
    )

    filepath = os.path.join(SITE, "decks", f"{deck['slug']}.html")
    with open(filepath, "w") as f:
        f.write(page)
    print(f"✅ {deck['slug']}.html ({len(deck['cards'])} cards)")

# Update catalog.json
with open(os.path.join(SITE, "decks", "catalog.json"), "r") as f:
    catalog = json.load(f)

for d in DECKS:
    catalog.append({
        "slug": d["slug"],
        "title": d["title"],
        "category": d["category"],
        "description": d["description"],
        "card_count": len(d["cards"]),
        "color": d["color"]["hex"],
    })

with open(os.path.join(SITE, "decks", "catalog.json"), "w") as f:
    json.dump(catalog, f, indent=2)

print(f"\n🎉 Generated {len(DECKS)} new deck pages")
print(f"📊 Total cards: {sum(len(d['cards']) for d in DECKS)}")
